spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true



